apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
        - name: phpldapadmin
          image: osixia/phpldapadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "openldap"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: phpldapadmin