apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trino-wk-pvc
  labels: {}
  annotations: {}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs
---
apiVersion: v1
kind: Pod
metadata:
  name: trino-woker-conf-mnt
spec:
  containers:
  - image: busybox
    name: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    volumeMounts:
        - mountPath: /etc/trino
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: trino-wk-pvc  # Reference the PVC