apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    volumeMounts:
        - mountPath: /opt/  # Mount the PVC to this path in the container
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: nfs-pvc  # Reference the PVC