apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  labels: {}
  annotations: {}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs