apiVersion: apps/v1
kind: Deployment
metadata:
   name: jupiter-spark
   namespace: spark-operator
   
spec:
   replicas: 1
   selector:
      matchLabels:
         app: spark
   template:
      metadata:
         labels:
            app: spark
      spec:
         serviceAccountName: spark-driver
         containers:
            - name: jupiter-spark-container
              image: bill/jupyter:0.0.4 #change with your image
              imagePullPolicy: Always
              ports:
              - containerPort: 8888
              env: 
              - name: JUPYTER_ENABLE_LAB
                value: "yes"
              - name: GRANT_SUDO
                value: "yes"
              - name: NB_USER
                value: "tyle"
              - name: CHOWN_HOME
                value: "yes"
              - name: CHOWN_HOME_OPTS
                value: "-R"
              resources:
                requests:
                  memory: "1Gi"  # Adjust the requested memory
                  cpu: "500m"    # Adjust the requested CPU
                limits:
                  memory: "2Gi"  # Adjust the maximum memory limit
                  cpu: "1"       # Adjust the maximum CPU limit
              volumeMounts:
              - name: jupyter-storage
                mountPath: /home/bill  # Change this to the path where you want to mount the volume
         volumes:
            - name: jupyter-storage
              persistentVolumeClaim:
               claimName: pvcju
---
apiVersion: v1
kind: Service
metadata:
   name: jupiter-spark-svc
   namespace: spark-operator
spec:
   type: NodePort
   selector:
      app: spark  
   ports:
      - port: 8888
        targetPort: 8888
        nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: jupiter-spark-driver-headless
  namespace: spark-operator
spec:
  clusterIP: None
  selector:
    app: spark