FROM trinodb/trino:436

USER root
RUN microdnf install -y gzip wget

COPY ranger-3.0.0-SNAPSHOT-trino-plugin.tar.gz /tmp/ranger-3.0.0-SNAPSHOT-trino-plugin.tar.gz
RUN tar -xzf /tmp/ranger-3.0.0-SNAPSHOT-trino-plugin.tar.gz

# elasticsearch compatibility fix
RUN rm -f /ranger-3.0.0-SNAPSHOT-trino-plugin/lib/ranger-trino-plugin-impl/lucene-core-*.jar
RUN wget -qO /ranger-3.0.0-SNAPSHOT-trino-plugin/lib/ranger-trino-plugin-impl/log4j-api-2.11.1.jar https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.11.1/log4j-api-2.11.1.jar
RUN wget -qO /ranger-3.0.0-SNAPSHOT-trino-plugin/lib/ranger-trino-plugin-impl/log4j-core-2.11.1.jar https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.11.1/log4j-core-2.11.1.jar
RUN wget -qO /ranger-3.0.0-SNAPSHOT-trino-plugin/lib/ranger-trino-plugin-impl/lucene-core-8.7.0.jar https://repo1.maven.org/maven2/org/apache/lucene/lucene-core/8.7.0/lucene-core-8.7.0.jar


COPY install.properties /ranger-3.0.0-SNAPSHOT-trino-plugin/
RUN chmod +x /ranger-3.0.0-SNAPSHOT-trino-plugin/install.properties

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# RUN chown -R trino:trino /ranger-3.0.0-SNAPSHOT-trino-plugin
# RUN chmod 644 -R /ranger-3.0.0-SNAPSHOT-trino-plugin

# changer permission to trino user
# RUN chown -R trino:trino /ranger-3.0.0-SNAPSHOT-trino-plugin/
RUN chmod 777 -R /ranger-3.0.0-SNAPSHOT-trino-plugin/

# RUN chown -R root:root /usr/lib/trino/plugin/
RUN chmod 777 -R /usr/lib/trino/plugin/

# RUN chown -R root:root /data/trino/
RUN chmod 777 -R /data/trino/

# RUN chown -R root:root /etc/trino/
RUN chmod 777 -R /etc/trino/

RUN chmod +x /ranger-3.0.0-SNAPSHOT-trino-plugin/enable-trino-plugin.sh
# USER trino
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
