apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: starburstdata/hive:3.1.2-e.18
          ports:
            - containerPort: 9083
          env:
            - name: HIVE_METASTORE_DRIVER
              value: "org.postgresql.Driver"
            - name: HIVE_METASTORE_JDBC_URL
              value: "jdbc:postgresql://metastore-db:5432/metastore"
            - name: HIVE_METASTORE_USER
              value: "hive"
            - name: HIVE_METASTORE_PASSWORD
              value: "123456"
            - name: HIVE_METASTORE_WAREHOUSE_DIR
              value: "s3://bill/"
            - name: S3_ENDPOINT
              value: "https://aaaaa.r2.cloudflarestorage.com"
            - name: S3_ACCESS_KEY
              value: "xxxxxxxxxxxxxxxxx"
            - name: S3_SECRET_KEY
              value: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            - name: S3_PATH_STYLE_ACCESS
              value: "true"
            - name: REGION
              value: ""
            - name: GOOGLE_CLOUD_KEY_FILE_PATH
              value: ""
            - name: AZURE_ADL_CLIENT_ID
              value: ""
            - name: AZURE_ADL_CREDENTIAL
              value: ""
            - name: AZURE_ADL_REFRESH_URL
              value: ""
            - name: AZURE_ABFS_STORAGE_ACCOUNT
              value: ""
            - name: AZURE_ABFS_ACCESS_KEY
              value: ""
            - name: AZURE_WASB_STORAGE_ACCOUNT
              value: ""
            - name: AZURE_ABFS_OAUTH
              value: ""
            - name: AZURE_ABFS_OAUTH_TOKEN_PROVIDER
              value: ""
            - name: AZURE_ABFS_OAUTH_CLIENT_ID
              value: ""
            - name: AZURE_ABFS_OAUTH_SECRET
              value: ""
            - name: AZURE_ABFS_OAUTH_ENDPOINT
              value: ""
            - name: AZURE_WASB_ACCESS_KEY
              value: ""
            - name: HIVE_METASTORE_USERS_IN_ADMIN_ROLE
              value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  type: ClusterIP
  ports:
    - port: 9083
      targetPort: 9083
  selector:
    app: hive-metastore
