apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranger-solr
  labels:
    app: ranger-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranger-solr
  template:
    metadata:
      labels:
        app: ranger-solr
    spec:
      containers:
      - name: ranger-solr
        image: bill/ranger-solr:0.0.1
        ports:
          - containerPort: 8983
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ranger-solr
spec:
  type: NodePort
  ports:
    - port: 8983
      targetPort: 8983
  selector:
    app: ranger-solr