apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranger-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranger-db
  template:
    metadata:
      labels:
        app: ranger-db
    spec:
      containers:
        - name: ranger-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "ranger"
            - name: POSTGRES_PASSWORD
              value: "ranger"
            - name: POSTGRES_DB
              value: "ranger"
---
apiVersion: v1
kind: Service
metadata:
  name: ranger-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: ranger-db